first_project/first_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("help", views.help, name="help"),
    path('template', views.template, name='template'),
    path("userinfo", views.userinfo, name="users"),
    path("forms", views.form_view, name="form_view"),
    path("index", views.index, name="index"),
    path("register", views.register, name="register"),
    path("logout", views.user_logout, name="logout"),
    path("special", views.special, name="special"),
    path("login", views.user_login, name="login"),
]

# TEMPLATE TAGGING

app_name = 'first_app'


first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    # path(r"^$", first_app.views.index, name = "url" ),
    path('first_app/', include('first_app.urls')),
    path('admin/', admin.site.urls),
    # path("", views.form_view, name="form_view")
]

first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name


class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.PROTECT)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name


class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.PROTECT)
    date = models.DateField()

    def __str__(self):
        return str(self.date)


class UserInfo(models.Model):
    first_name = models.CharField(max_length=264, unique=True)
    last_name = models.CharField(max_length=264, unique=True)
    email_id = models.EmailField()

    def __str__(self):
        return self.first_name


class UserProfileUpdate(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)

    # additional classes
    user_portfolio = models.URLField(blank=True)
    user_image = models.ImageField(upload_to="profile_pic", blank=True)


    def __str__(self):
        return self.user.username



first_project/first_app/forms.py
from django import forms
from django.core import validators
from .models import AccessRecord,Webpage,Topic,UserInfo, UserProfileUpdate
from django.contrib.auth.models import User


class MyNewForm(forms.ModelForm):

    class Meta:
        model = UserInfo
        fields = "__all__"


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    # user_url = forms.URLField(label="Update the profile URL here")
    # user_image = forms.ImageField(label="Update your profile image here")

    class Meta:
        model = User
        fields = ("username", "email", "password")


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfileUpdate
        fields = ("user_portfolio", "user_image")








# custom validators need an keyword argument("value") this tells django that it is a validator.
# This is for a single check.
def check_for_a(value):
    if value[0].lower() != "a":
        raise forms.ValidationError("Name should start with a")


class FormName(forms.Form):
    name = forms.CharField(validators=[check_for_a])
    # cake = forms.DateField(widget=forms.DateInput)
    email = forms.EmailField()
    verify_email = forms.EmailField(label="Enter your email again")
    Remarks = forms.CharField(widget=forms.Textarea)
    # botcatcher = forms.CharField(required=False, widget=forms.HiddenInput,
    #                              validators=[validators.MaxLengthValidator(0)])







    # To clean check all the form at once we can do this:
    def clean(self):
        all_clean_data = super(FormName, self).clean()
        email = all_clean_data["email"]
        verify_email = all_clean_data["verify_email"]

        if email != verify_email:
            raise forms.ValidationError("Email dont match.")


    # def clean_botcatcher(self):
    #     botcatcher = self.cleaned_data["botcatcher"]
    #     if len(botcatcher) > 0:
    #         raise forms.ValidationError("GOTCHA BOT!")
    #
    #     return botcatcher

first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from .models import Topic, Webpage, AccessRecord, UserInfo, UserProfileUpdate
from .forms import MyNewForm, FormName, UserUpdateForm, UserForm
from django import forms

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
# Create your views here.


def index(request):
    context_dict = {"text": "you are using template filters here to title case this content"}
    return render(request, "first_app/index.html",context=context_dict)


def template(request):
    webpages_list = AccessRecord.objects.order_by("date")
    date_dict = {"access_records": webpages_list}

    # my_dict = {"insert_me":"Hello I am from first_app/views.py"}
    return render(request, "first_app/basic_templates.html", context=date_dict)


def help(request):
    my_dict = {"help_Page": "I needed help so i visited this page"}
    return render(request, "first_app/help.html", context=my_dict)


def userinfo(request):
    form = MyNewForm()

    if request.method == "POST":
        form = MyNewForm(request.POST)

        if form.is_valid():
            form.save()

            return index(request)

        else:
            forms.ValidationError("Please fill the fields correctly")
            print("Error: invalid Data")

    return render(request, "first_app/users.html", {"form": form})

    # user_list = Users.objects.order_by("first_name")
    # user_dict = {"user_list": user_list}
    # return render(request, "first_app/users.html", context=user_dict)


@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/first_app/user_login/'
    return HttpResponse("You are logged in. Nice!")

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect("register")

def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserUpdateForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if "user_image" in request.FILES:
                profile.user_image = request.FILES["user_image"]

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserUpdateForm()

    return render(request, "first_app/registration.html", {"user_form": user_form,
                                                           "profile_form": profile_form,
                                                           "registered": registered})


def user_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect("index")

            else:
                return HttpResponse("Account is not active")

        else:
            print("Someone tried to login and failed")
            print(f"username:{username}, password: {password}")
            return HttpResponse("invalid login details supplied!")

    else:
        return render(request, "first_app/login.html", {})


def form_view(request):
    form = FormName()

    if request.method == "POST":
        form = FormName(request.POST)


        if form.is_valid():
            print("Your data is valid")
            print(f"Name: {form.cleaned_data['name']}")
            print(f"Email: {form.cleaned_data['email']}")
            print(f"Remarks: {form.cleaned_data['Remarks']}")
    return render(request, "first_app/basic_forms.html", {'form': form})


first_project/templates/first_app/basic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BASE</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <div class="navbar-nav ">

            <ul class="nav navbar-nav me-auto mb-2 mb-lg-0">
                <li><a class="navbar-brand" href="#">BRAND</a></li>
                <li><a class="nav-item nav-link active" href="{% url 'admin:index' %}">admin</a></li>
                <li><a class="nav-item nav-link active" href=" {% url 'first_app:users' %}">users</a></li>
                <li><a class="nav-item nav-link active" href=" {% url 'first_app:register' %}">Register</a></li>

                {% if user.is_authenticated %}
                    <li><a class="nav-link" href="{% url 'first_app:logout' %}">Logout</a></li>
                {% else %}
                    <li><a class="nav-link" href="{% url 'first_app:login' %}">Login</a></li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>


    <div class="container">
        {% block body_block %}
        # anything outside this will be inherited if you extend
        {% endblock %}
    </div>

</body>
</html>

first_project/templates/first_app/basic_forms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Form Demo</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<body>
    <h1>We are at forms page. We can collect the data and print the given data in the terminal.</h1>
    <div class="container">
        <form  method="POST">
            {{ form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="submit">
        </form>
    </div>

</body>
</html>

first_project/templates/first_app/basic_templates.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>First App</title>
    <link rel="stylesheet" href="{% static 'CSS\mystyle.css' %}">
</head>
<style>
    h1{
    color:blue;
    }
    table{
    border: 2px solid black;
    }
    tr{
    border: 2px solid black;}
</style>
<body>
    <h1>Hello, we are getting the below data using template tagging.</h1>
    <div class="MVT">
    {% if access_records %}
    <table>
        <thead>
        <th>Site Name</th>
        <th> Date Accessed</th>
        </thead>
        {% for acc in access_records %}
        <tr>
            <td>{{acc.name}}</td>
            <td>{{acc.date}}</td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
        <h2>No records to show!</h2>
    {% endif %}

    </div>
</body>
</html>

first_project/templates/first_app/help.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>help_Page</title>
    <link rel="stylesheet" href="{% static 'CSS/mystyle.css'%}">
</head>
<body>
    <h1>This is the help page</h1>
    <img src="{% static 'images/img_1.png' %}" alt="No image to show" >

</body>
</html>

first_project/templates/first_app/index.html
<!DOCTYPE html>
{% extends "first_app/basic.html" %}
{% block body_block %}
    <h1>This is the index page!</h1>
<!--    <strong>{{ text|title }}</strong>-->
<!--    <a href="{% url 'first_app:help' %}"><p>Lets go to help page</p></a>-->
<!--    <a href="{% url 'first_app:users' %}">This is users page</a>-->
{% endblock %}

first_project/templates/first_app/login.html
<!DOCTYPE html>
{% extends "first_app/basic.html" %}
{% load static %}
{% block body_block %}

<div class="jumbotron">
    <h1> Please Login</h1>
    <form action="{% url 'first_app:login'%}" method="POST">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" value="Login">

    </form>
</div>


{% endblock%}

first_project/templates/first_app/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

first_project/templates/first_app/registration.html
<!DOCTYPE html>
{% extends "first_app/basic.html" %}
{% load static %}
{% block body_block %}

<div class="container">
    {% if registered %}
        <h2> Thank you for registering with us!</h2>
    {% else %}
        <h1> Register here!</h1>
        <h3> Fill out the form:</h3>

        <form  enctype="multipart/form-data" method="POST" >
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" value="Register">

        </form>

    {% endif %}
</div>
{% endblock %}

first_project/templates/first_app/users.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Users</title>
    <link rel="stylesheet" href="{% static 'CSS/mystyle.css' %}">

</head>
<body>

    <div class="container">
        <h1>Lets sign you up using Django forms </h1>
        <form  method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
        </form>
    </div>







<!--    <h1> <strong>Here are the list of users and their data:</strong></h1>-->
<!--    <div class="user_list">-->
<!--    {% if user_list %}-->
<!--        <ol>-->

<!--                {% for user in user_list %}-->
<!--            <li> User info:-->
<!--                <ul>-->
<!--                    <li> First Name:{{user.first_name}}</li>-->
<!--                    <li>Last Name:{{user.last_name}}</li>-->
<!--                    <li> Email:{{user.email_id}}</li>-->
<!--                </ul>-->
<!--            </li>-->
<!--            {% endfor %}-->
<!--        </ol>-->
<!--    {% endif %}-->
<!--    </div>-->


</body>
</html>